
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["github.com/hashicorp/vault/api*"]

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "16.0.0"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "1.0.1"

[[constraint]]
  name = "github.com/hashicorp/consul-template"
  version = "v0.19.5"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

# This package doesn't allow testing on mac beyond v4.1.0 due to a function that
# only builds on other platforms.  Pinning version for now.
[[override]]
  name = "github.com/godbus/dbus"
  version = "4.1.0"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/yaml.v1"
